print("")
valor_Escolhido = float(input("Digite um valor inteiro qualquer: "))
print("")
print("O valor escolhido é: {}".format(valor_Escolhido))
print("")
valor_Dobrado = (valor_Escolhido * 2)
print("O dobro do valor escolhido é: {}".format(valor_Dobrado))
print("")
valor_Triplo = (valor_Escolhido * 3)
print("O tripo do valor escolhido é: {}".format(valor_Triplo))
print("")
valor_Raiz = (valor_Escolhido ** (1/2))
print("A raiz quadrada do valor escolhido é: {:.2f}".format(valor_Raiz))
print("")

