print("")
print("Curso em Vídeo")
print("Desafios de Python")
print("")
numero_Inteiro = int(input("Digite um número inteiro qualquer: "))
numero_Anterior = (numero_Inteiro - 1)
numero_Posterior = (numero_Inteiro + 1)
print("")
print("O número escolhido foi: {}".format(numero_Inteiro))
print("")
print("O número anterior é: {} e o número posterior é: {}".format(numero_Anterior, numero_Posterior))
print("")
